services:
  - name: aimock-test-service
    labels:
      deployment: default
    upstream:
      name: aimock-upstream
      scheme: http
      nodes:
        - host: ${MOCK_HOST}
          port: ${MOCK_PORT}
          weight: 1
    routes:
      - uris:
          - /v1/chat/completions
        name: aimock-test-route
        methods:
          - POST
        plugins:
          ai-proxy:
            provider: openai
            auth:
              header:
                Authorization: Bearer sk-1234567890abcdef1234567890abcdef12345678 # dummy value
            options:
              model: gpt-5
            override:
              endpoint: http://${MOCK_HOST}:${MOCK_PORT}/v1/chat/completions
global_rules:
  prometheus:
    _meta:
      disable: true
    prefer_name: false
